name: MusicAssistantPlayer
options:
  bundleIdPrefix: com.harperreed
  deploymentTarget:
    macOS: "14.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages:
  MusicAssistantKit:
    url: https://github.com/harperreed/MusicAssistantKit.git
    from: 0.0.4
  ResonateKit:
    url: https://github.com/harperreed/ResonateKit.git
    from: 0.3.4

targets:
  MusicAssistantPlayer:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - Sources/MusicAssistantPlayer
      - path: Resources
        type: folder
        buildPhase: resources
    dependencies:
      - package: MusicAssistantKit
      - package: ResonateKit
    settings:
      base:
        PRODUCT_NAME: MusicAssistantPlayer
        PRODUCT_BUNDLE_IDENTIFIER: com.harperreed.musicassistantplayer
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/MusicAssistantPlayer.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ICON_FILE: AppIcon.icns
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
        OTHER_CODE_SIGN_FLAGS: "--timestamp"
        COMBINE_HIDPI_IMAGES: YES

  MusicAssistantPlayerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/MusicAssistantPlayerTests
    dependencies:
      - target: MusicAssistantPlayer
